### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by sapshah** [claabs/puppeteer-extra-plugin-portal#4]
When I try to build, it gives the error as following:
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective 
  at $PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/ts-loader/dist/servicesHost.js:713:18
    at $PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/ts-loader/dist/servicesHost.js:128:141
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives ($PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/ts-loader/dist/servicesHost.js:128:124)
    at actualResolveTypeReferenceDirectiveNamesWorker ($PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/typescript/lib/typescript.js:118257:163)
    at resolveTypeReferenceDirectiveNamesWorker ($PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/typescript/lib/typescript.js:118557:26)
    at processTypeReferenceDirectives ($PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/typescript/lib/typescript.js:120054:31)
    at findSourceFileWorker ($PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/typescript/lib/typescript.js:119939:21)
    at findSourceFile ($PATH/puppeteer-extra-plugin-portal-master/frontend/node_modules/typescript/lib/typescript.js:119791:26)

**Comment by rublev** [comment]
same
